import {
  FAROLBG,
  MPBG,
  PARQUET,
  FAROL,
  PLANILHAFAROL,
  PLANILHAPARQUET,
  ARROW,
  REPOSITORIO,
  SEARCH,
  CLOCK,
  DOCFAROL,
  DOCPARQUET,
  ROBOT,
} from './index';

export const MOCKPRODUTOSHEADER = [
  {
    id: 'MPRJDigital',
    imgBg: MPBG,
    colorBtn: '#C99E50',
    colorBar: '#702826',
    corTitleBtn: '#FFF',
    titleBtn: 'Procurar',
    icon1: REPOSITORIO,
    title1: 'Repositório',
    icon2: SEARCH,
    title2: 'Nome da Base',
    icon3: ARROW,
    title3: 'Qualidade da Base',
    icon4: CLOCK,
    title4: 'Última Atualização',
  },
  {
    id: 'Farol',
    imgBg: FAROLBG,
    colorBtn: '#CCB0A3',
    colorBar: '#AB662C',
    corTitleBtn: '#FFFF',
    titleBtn: 'Procurar',
    icon1: FAROL,
    title1: 'Conheça o Farol',
    icon2: PLANILHAFAROL,
    title2: 'Planilhas',
    icon3: DOCFAROL,
    title3: 'Documentos',
    icon4: DOCFAROL,
    title4: 'Notas Técnicas',
  },
  {
    id: 'ParquetDigital',
    imgBg: PARQUET,
    colorBtn: '#82D4FF',
    colorBar: '#3781BD',
    corTitleBtn: '#FFF',
    titleBtn: 'Procurar',
    icon1: ROBOT,
    title1: 'Um Robô em cada Promotoria',
    icon2: PLANILHAPARQUET,
    title2: 'Perfil de Atuação',
    icon3: DOCPARQUET,
    title3: 'Documentos',
    icon4: DOCPARQUET,
    title4: 'Documentação',
  },
];
export default MOCKPRODUTOSHEADER;
