export { default as Footer } from './footer/Footer';
export { default as Header } from './header/Header';
export { default as MprjDigital } from './mprjDigital/MprjDigital';
export { default as Mprj } from './mprj/Mprj';
export { default as NavBar } from './navbar/Navbar';
export { default as OpenData } from './openData/OpenData';
export { default as Partners } from './partners/Partners';
export { default as Products } from './products/Products';
export { default as Repos } from './repos/Repos';
